# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sandeep Aggarwal
tagline:             'A Digital Carpenter'
description:         Premature optimzation is the root of all evil. Here lies my premature optimized thoughts.
url:                 https://sanagrwl.github.io/
paginate:            5

# About/contact
author:
  name:              Sandeep Aggarwal
  url:               https://sanagrwl.github.io/

# Custom vars
version:             1.0.0
